### ISSUE TITLE
complete and fill with tidyr

### ISSUE THREAD

**Issue by crosecrans-usgs** [USGS-R/hypeRusgs#3]
Trying to create a simple bar plot in ggplot using geom_col, but input dataset does not have complete cases across all variables that I am looking to plot, therefore column widths in geom_col are not uniform. I believe I need to use tidyr complete and fill on the dataset so, but having difficulty  figuring it out.  Attached is the dataset and Rcode for creating 2 example plots.  I would like the column widths to be uniform for all x axis values (explanatory factors).

[spearmans_rho_czr.zip](https://github.com/USGS-R/hypeRusgs/files/2116872/spearmans_rho_czr.zip)

**Comment by lindsayplatt** [comment]
You could fill the dataset so that all unique combinations of what you are looking for are available so that the bars are sized the same. And the easiest way to do this is to use `tidyr::complete`. Although, there's an alternative that would not result in so much empty space. Here is the stackoverflow example that I was working from: https://stackoverflow.com/questions/38101512/the-same-width-of-the-bars-in-geom-barposition-dodge.

```
# Setup for libraries and data
library(dplyr)
library(tidyr)
library(ggplot2)

# used `dput` from after loading in your files to get copy/pastable example.

test.AS <- structure(list(exp.fact = structure(c(1L, 3L, 11L, 9L, 7L, 4L, 1L, 3L, 7L, 2L, 11L, 12L, 1L, 2L), .Label = c("Aridity.Index", "DO", "ELEV_VA", "HCO3", "PctIrr_buffer", "PctIrr_cell", "PH_F", "prct.Ag", "prct.Natural", "prct.Urban", "TDS", "WELL_DEPTH_VA"), class = "factor"), rho = c(-0.753846154, -0.793406593, 0.56043956, 0.225667977, 0.36612914, -0.272656571, -0.531562205, -0.361961403, 0.406590507, -0.53343894, 0.372627487, -0.221547587, -0.359686211, 0.513445257), pvalue = c(0.002749006, 0.001150904, 0.04013504, 0.046969647, 0.000978549, 0.01573049, 1.24112e-05, 0.004485812, 0.001265549, 1.14103e-05, 0.003367511, 0.048266787, 0.005142067,3.20105e-05), spearman.name = structure(c(1L, 1L, 1L, 18L, 18L, 18L, 81L, 81L, 81L, 81L, 81L, 59L, 31L, 31L), .Label = c("bnrc_GW_Arsenic", "bnrc_GW_CL", "bnrc_GW_CL3_THM", "bnrc_GW_FE", "bnrc_GW_Fluoride", "bnrc_GW_MN", "bnrc_GW_RAD226_228", "bnrc_GW_RN_222", "bnrc_GW_SB","bnrc_GW_SO4", "bnrc_GW_SR", "bnrc_GW_TDS", "bnrc_Spring_RN_222", "bnrc_Spring_SO4", "bnrc_Spring_TDS", "bnrc_Spring_TI", "bnrf_ALPHA_72H", "bnrf_Arsenic", "bnrf_CL", "bnrf_CL3_THM", "bnrf_FE", "bnrf_Fluoride", "bnrf_MN", "bnrf_MO", "bnrf_NO3_N", "bnrf_SO4", "bnrf_SR", "bnrf_TDS", "bnrf_U_UG", "clpt_ALPHA_30D", "clpt_Arsenic", "clpt_Atrazine", "clpt_CL", "clpt_CL3_THM", "clpt_FE", "clpt_Fluoride", "clpt_MN", "clpt_MO", "clpt_NO3_N", "clpt_SO4", "clpt_TDS", "clpt_U_UG", "colpt_ALPHA_30D", "colpt_ALPHA_72H", "colpt_CL", "colpt_CL3_THM", "colpt_FE", "colpt_Fluoride", "colpt_MN", "colpt_NO3_N", "colpt_RAD226_228", "colpt_RN_222", "colpt_SO4", "colpt_SR", "colpt_TDS", "colpt_U_UG", "hpaq_ALPHA_30D", "hpaq_ALPHA_72H", "hpaq_Arsenic", "hpaq_Atrazine", "hpaq_BDCM_THM", "hpaq_Bromacil", "hpaq_CAAT", "hpaq_CL", "hpaq_CL3_THM", "hpaq_FE", "hpaq_Fluoride", "hpaq_MN", "hpaq_MO", "hpaq_NO3_N", "hpaq_Perchlorate", "hpaq_PROPAZINEN", "hpaq_RN_222", "hpaq_SE", "hpaq_SO4", "hpaq_SR", "hpaq_TDS", "hpaq_U_UG", "rgaq_ALPHA_30D", "rgaq_ALPHA_72H", "rgaq_Arsenic", "rgaq_CL", "rgaq_CL3_THM", "rgaq_FE", "rgaq_Fluoride", "rgaq_MN", "rgaq_MO", "rgaq_NO3_N", "rgaq_Perchlorate", "rgaq_RN_222", "rgaq_SO4", "rgaq_SR", "rgaq_TDS", "rgaq_U_UG"), class = "factor"), PAS = structure(c(1L, 1L, 1L, 2L, 2L, 2L, 6L, 6L, 6L, 6L, 6L, 5L, 3L, 3L), .Label = c("bnrc", "bnrf", "clpt", "copl", "hpaq", "rgaq"), class = "factor"), const.name = structure(c(4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L), .Label = c("ALPHA_30D", "ALPHA_72H", "Antimony", "Arsenic", "Atrazine", "BDCM_THM", "Bromacil", "CAAT", "Chloride", "CL3_THM", "FE", "Fluoride", "MN", "MO", "NO3_N", "Perchlorate", "Propazine", "Radium Activity", "Radon-222", "RN_222", "SE", "SO4", "Strontium", "TDS", "thallium", "Uranium"), class = "factor"), site.type = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("GW", "spring"), class = "factor")), .Names = c("exp.fact", "rho", "pvalue", "spearman.name", "PAS", "const.name", "site.type"), class = "data.frame", row.names = c(NA, -14L))

```

### Using `tidyr::complete` to handle varying bar width

As you noted the bars are sized various widths if there are missing values:

```
#arsenic plot is not good
ggplot(data= test.AS,aes(x=exp.fact,y=rho,fill=PAS))+
  geom_col(position= "dodge")+
  geom_hline(linetype="solid", colour="black",yintercept=0)+
  labs(subtitle= "Arsenic")
```

![image](https://user-images.githubusercontent.com/13220910/41938221-17d16906-7958-11e8-8c52-8357edf207f3.png)

You want a plot with one bar for every `exp.fact` and `PAS` combination. Therefore, you specify both of those columns in your `complete` function. Then the unique combinations of `exp.fact` and `PAS` that are not represented will be filled with NA. The key part that makes this easy for your data, is that you have factors for the `exp.fact` and `PAS` columns. So, based on the help for the function `tidyr::complete`, "For factors, the full set of levels (not just those that appear in the data) are used.". 

```
test.AS.filled <- test.AS %>% complete(exp.fact, PAS)

ggplot(data= test.AS.filled, aes(x=exp.fact,y=rho,fill=PAS))+
  geom_col(position= "dodge")+
  geom_hline(linetype="solid", colour="black",yintercept=0)+
  labs(subtitle= "Arsenic")
```

![image](https://user-images.githubusercontent.com/13220910/41938267-39381db0-7958-11e8-91ca-b77c208c3bd2.png)

Although, that's not exactly right because now we have tons of missing data. What we really want is for every represented `exp.fact` (not every unique one) to exist, and then add space for the missing `PAS` bars. You can do this by first grouping by `exp.fact` and then using `complete`.

```
test.AS.filled.group <- test.AS %>% group_by(exp.fact) %>% complete(PAS)

ggplot(data= test.AS.filled.group, aes(x=exp.fact,y=rho,fill=PAS))+
  geom_col(position= "dodge")+
  geom_hline(linetype="solid", colour="black",yintercept=0)+
  labs(subtitle= "Arsenic")
```
![image](https://user-images.githubusercontent.com/13220910/41939251-c7da246c-795a-11e8-89eb-efc1963e4a78.png)

### Faceting to handle varying bar width

The easiest thing to do (if you don't need to represent the missing combinations with space) is to use faceting. Facet by the `exp.fact` to group the bars along the x-axis. Then, put the PAS as the variable along the X and specify that spacing and scales along the x should be "free". This means the facets can expand or contract (based on number of bars needed) independently of the others. No need to manipulate the data.

```
ggplot(data= test.AS,aes(x=PAS,y=rho,fill=PAS))+
  geom_col(position= "dodge")+
  geom_hline(linetype="solid", colour="black",yintercept=0)+
  labs(subtitle= "Arsenic") +
  facet_grid(~exp.fact, scales = "free_x", space = "free_x")
```

![image](https://user-images.githubusercontent.com/13220910/41939274-db5f9d50-795a-11e8-9968-fe50cd04ba4d.png)

**Comment by crosecrans-usgs** [comment]
Thank you Lyndsay, this is great.  Exactly what I was looking to depict.

Thank you again, Celia

**Comment by lindsayplatt** [comment]
Covered in the 6/27 session.
