### ISSUE TITLE
Turn NADAList into data frame

### ISSUE THREAD

**Issue by jlevitt-USGS** [USGS-R/hypeRusgs#5]
[R_training_NADA_Levitt.xlsx](https://github.com/USGS-R/hypeRusgs/files/2206272/R_training_NADA_Levitt.xlsx)

#Use NADA to determine chloride summary statistics for each town
#Read in R_training_NADA_Levitt.xlsx and name the data frame "usgs"

library("NADA")
#Estimate the ECDF using the Kaplan-Meier method 
cenfit<-with(usgs,cenfit(Chloride, as.logical(cens), groups = as.factor(TOWN))) 

#Calculate the percentiles of concentration values for each town
quantile<-quantile(cenfit)
show(quantile)

#How do I get this list into a data frame with TOWN as the first column and the percentiles as the following columns?

**Comment by lindsayplatt** [comment]
I would use a combination of `lapply` and `dplyr::bind_rows`.

First, I subsetted the data using `dplyr::sample_n`, made TOWN a factor before the function, and then used `cenfit` and created the `quantile_result` vector.

```
usgs <- structure(list(TOWN = structure(c(10L, 6L, 2L, 1L, 4L, 8L, 5L, 
9L, 3L, 7L), .Label = c("BRIDPORT", "CASTLETON", "CHESTER", "EDEN", 
"GREENSBORO", "HINESBURG", "JOHNSON", "STARKSBORO", "WILLISTON", 
"WOODSTOCK"), class = "factor"), Chloride = c(0, 37, 0, 24, 166, 
0, 10, 99, 10, 0), cens = c("TRUE", "FALSE", "TRUE", "FALSE", 
"FALSE", "TRUE", "FALSE", "FALSE", "FALSE", "TRUE")), .Names = c("TOWN", 
"Chloride", "cens"), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-10L))

# Change groups into factors before cenfit
usgs <- dplyr::mutate(usgs, TOWN = as.factor(TOWN))

#Estimate the ECDF using the Kaplan-Meier method
cenfit <- with(usgs, cenfit(Chloride, as.logical(cens), groups = TOWN))

#Calculate the percentiles of concentration values for each town
quantile_result <- quantile(cenfit)
```

Now, I use an lapply across `1:length(quantile_result)` rather than lapply on the quantile list because I want the town names which are the names of each list element. I pass in the full list, and names of the list in addition to what's being iterated over (`i`). Then, I can use `dplyr::bind_rows` to convert the list of data frames into one single data frame (assuming they have the same columns).

```
x <- c("A", "B", "C", "D")
ex_list <- lapply(1:4, FUN = function(i, x) { 
  return(paste(x[i], i)) 
}, x = x)

quantile_result[1]
quantile_result[[1]]
names(quantile_result)

complete_list <- lapply(seq_along(quantile_result), function(i, list_quantile, names_town) {
  
  # Create data.frame using town name, the values, and percentile names
  percentiles_df <- data.frame(Town = gsub("TOWN=", "", names_town[i]),
                               Value = list_quantile[[i]], 
                               Percentile = names(list_quantile[[i]]),
                               stringsAsFactors = FALSE)
  
  # Use `tidyr::spread` to get each percentile as a column
  percentiles_df <- tidyr::spread(percentiles_df, 
                                  key = Percentile, 
                                  value = Value)
  
  # Columns get alphabetized when this happens, so reorder after
  percentiles_df <- dplyr::select(percentiles_df, Town, names(list[[i]]))
  
  return(percentiles_df)
  
}, list_quantile = quantile_result, names_town = names(quantile_result))

complete_df <- dplyr::bind_rows(complete_list)

```

The output looks something like this:
```
complete_df
         Town 5% 10% 25% 50% 75% 90% 95%
1    BRIDPORT NA  NA  NA  NA  NA  NA  NA
2   CASTLETON NA  NA  NA  NA  NA  NA  NA
3     CHESTER NA  NA  NA  NA  NA  NA  NA
4        EDEN NA  NA  NA  NA  NA  NA  NA
5  GREENSBORO NA  NA  NA  NA  NA  NA  NA
6   HINESBURG NA  NA  NA  NA  NA  NA  NA
7     JOHNSON NA  NA  NA  NA  NA  NA  NA
8  STARKSBORO NA  NA  NA  NA  NA  NA  NA
9   WILLISTON NA  NA  NA  NA  NA  NA  NA
10  WOODSTOCK NA  NA  NA  NA  NA  NA  NA
```

**Comment by jlevitt-USGS** [comment]
This seems to solve the problem. Thank you. 

My only other question is how, for certain towns, the quantile(cenfit) function produces results where a well may have a 90% concentration estimated from the Kaplan-Meier method but will have no value for the 95%. 

Please see attached final table. Two town examples are Alburgh or Barnard. This must be an artifact of the way that the estimation is calculated and any help would be greatly appreciated from those familiar with the cenfit() function. Thank you.

[quantile_KM_Cl.xlsx](https://github.com/USGS-R/hypeRusgs/files/2223662/quantile_KM_Cl.xlsx)

**Comment by lindsayplatt** [comment]
@jlevitt-USGS since I have never used this package, this gets a bit beyond my expertise. I would suggest contacting the package maintainer with this question about how the estimations are calculated. Remember to send them a reproducible example (so try to use `dput()` with just the problem data to create a small data.frame rather than send a full excel file).

https://cran.r-project.org/web/packages/NADA/NADA.pdf

**Comment by lindsayplatt** [comment]
Covered in the 7/25 session.
