### ISSUE TITLE
when ifelse() statements evaluate to NA and other NA properties

### ISSUE THREAD

**Issue by kransom14** [USGS-R/hypeRusgs#7]
I am hoping we can discuss something to watch out for when using ifelse(). When using ifelse() on a column to determine the value of a second column, NA in the first column will be preserved. This may or may not be a desired effect. Can we discuss more and include more examples? Such as testing for is.na() within ifelse()? Or other properties of NA when working with data? 

```r
d <- data.frame(site = LETTERS[1:5], limit = c(NA, "<", "<", NA, "V"), obs = c(1.3, 1, 2, 5, 4))
# I want to make a new obs column for when the limit code is "V", but this makes NA
# for any row where limit is NA
n <- d %>% mutate(obs_new = ifelse(limit == "V", NA, obs))

# using %in% will solve the problem
n <- d %>% mutate(obs_new = ifelse(limit %in% "V", NA, obs))
```

**Comment by kransom14** [comment]
We should also discuss blanks versus NA. For example when a csv or xls is read in with blanks and na.strings = "" is not set. The R data frame will have blanks. These blanks don't behave the same as NA in R. They could be treated as a category in factor variables.

**Comment by ldecicco-USGS** [comment]
`NA`'s are tricky. In your example, what I'd do is:
```r
d$obs_new <- d$obs
d$obs_new[d$limit == "V"] <- NA
```

I'm not 100% sure if in your second comment, you are referring to csv/xls files that already exist with NA's and blanks, or if you are saving from R. Either way...lot's of good discussion points!

**Comment by ldecicco-USGS** [comment]
What I described above is called "conditional indexing". When people are taught `dplyr` first...they tend to forget (or may have never learned) that conditional indexing is an extremely efficient and useful in many ways. I did a test on your data frame (I had to make it much bigger to show the time difference accurately:

```r
d <- data.frame(site = rep(LETTERS[1:5],1000000), 
                limit = rep(c(NA, "<", "<", NA, "V"),1000000),
                obs = rep(c(1.3, 1, 2, 5, 4),1000000))

system.time({
  d <- d %>% mutate(obs_new = ifelse(limit %in% "V", NA, obs))
})
   user  system elapsed 
   0.43    0.17    0.59 
d <- data.frame(site = rep(LETTERS[1:5],1000000), 
                limit = rep(c(NA, "<", "<", NA, "V"),1000000),
                obs = rep(c(1.3, 1, 2, 5, 4),1000000))
system.time({
  d$obs_new <- d$obs
  d$obs_new[d$limit == "V"] <- NA
})
   user  system elapsed 
   0.04    0.05    0.08 
```
I find this conditional indexing to be really useful, and one big reason is how `NA`'s work out. Several layers of nested `ifelse`'s I think also come out cleaner with this workflow. For example:
```r
  d$obs_new <- d$obs
  d$obs_new[d$limit == "V"] <- NA
  d$obs_new[d$limit == ">"] <- Inf
```

But....maybe it makes more sense in your workflow to keep piping through some `dplyr` code. Then what? The function `case_when` is super nice alternative to `ifelse`. As for efficiency, it's similar to `ifelse` (that is...it's still faster to use the conditional indexing I show above), but...it's more flexible and easily pipable:

```r
d <- d %>% mutate(obs_new = case_when(limit == "V" ~ NA_real_,
                                      TRUE ~ obs))
```
What's going on there? The new column is being created with `mutate`. `case_when` then looks at the "limit" column. If it's equal to "V", it sets obs_new to `NA`, and anything else is set to the obs column. A few tricks you need to know... you need to use `NA_real_` instead of `NA` because `dplyr` is assuming the `NA` is a logical `NA` and not a numeric `NA`...so it will error unless you clearly specify `NA_real_` (which is the numerical version of `NA`....,most other functions don't need that distinction...but this one does). That last `TRUE ~ obs` is the "catch-all" end case. The `~` are creating formulas. Formulas can be really powerful in R....maybe a topic of conversation for some future R lunch bunch. For now, you can read that line as "if limit is equal to "V" make the column NA, if not, obs". If you wanted a few more conditions:

```r
mutate(obs_new = case_when(limit == "V" ~ NA_real_,
                           limit == ">" ~ Inf,
                           TRUE ~ obs))
```
https://dplyr.tidyverse.org/reference/case_when.html

Some other functions to keep in mind:

```r
is.na
isTRUE
all
any
na.omit
&& 
&
||
|
```

**Comment by ldecicco-USGS** [comment]
https://stackoverflow.com/questions/6558921/boolean-operators-and

**Comment by ldecicco-USGS** [comment]
Covered in the 8/29 lesson
